
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      - name: registry-data
        emptyDir: {}       # for testing; switch to a PVC in prod

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
