apiVersion: v1
kind: Service
metadata:
  name: pythontest
  labels:
    app: pythontest
spec:
  selector:
    app: pythontest
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 31000
      protocol: TCP
